//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceEntry
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public System.TimeSpan EntryTime { get; set; }
        public Nullable<System.TimeSpan> ExitTime { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
