//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbERPEntities : DbContext
    {
        public dbERPEntities()
            : base("name=dbERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employeeInformation> employeeInformations { get; set; }
        public virtual DbSet<CompanyInformation> CompanyInformations { get; set; }
        public virtual DbSet<DepartmentInformation> DepartmentInformations { get; set; }
        public virtual DbSet<AttendanceEntry> AttendanceEntries { get; set; }
        public virtual DbSet<LeaveEntry> LeaveEntries { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
    }
}
